name: Github CI - Development

on:
  push:
    branches: [ develop, master ]

jobs:
  setup-and-build:
    name: Setup and build
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: 📁 Check out the repository
        uses: actions/checkout@v5.0.1

      - name: 📦 Cache Rust toolchain
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: rust-toolchain-

      - name: 🛠️ Set up Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          components: rustfmt, clippy

      - name: ✅ Check with Clippy linter
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

      - name: 💄 Format code with Cargo formatter
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: 🦀 Install Rust dependencies and build library
        uses: actions-rs/cargo@v1
        with:
          command: build

  integration-tests:
    name: Integration tests
    runs-on: ubuntu-latest
    needs: setup-and-build
    permissions:
      contents: read
    env:
      COMPOSE_PROJECT_NAME: "paperless-ngx"

    steps:
      - name: 📁 Check out the repository
        uses: actions/checkout@v5.0.1

      - name: 📦 Cache Rust toolchain
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: rust-toolchain-

      - name: 🛠️ Set up Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

#      - name: 🐳 Set up docker and containers
#        run: |
#          docker-compose --file docker-compose.yml pull --quiet
#          docker-compose run --rm webserver createsuperuser
#
#          docker-compose --file docker-compose.yml up --detach

#      - name: 🧪 Run integration tests
#        uses: actions-rs/cargo@v1
#        with:
#          command: test
#          args: -- --test-threads=1